security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="consumer" password="consumer-password";
ssl.keystore.location=/etc/kafka/secrets/kafka-0.keystore.jks
ssl.keystore.password=password
ssl.key.password=password
ssl.truststore.location=/etc/kafka/secrets/kafka-0.truststore.jks
ssl.truststore.password=password
ssl.endpoint.identification.algorithm=
